<?php

namespace AppBundle\Repository;

/**
 * sousEspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sousEspaceRepository extends \Doctrine\ORM\EntityRepository
{
}
